import { ThemeOptions } from "./types";

const ThemeCssVars = (theme: ThemeOptions) => {

    const shadows: any = {}
    theme.shadow.forEach((s, i) => shadows[`--shadow-${i}`] = s)

    return {
        "--bp-xs": theme.breakpoints.xs,
        "--bp-sm": theme.breakpoints.sm,
        "--bp-md": theme.breakpoints.md,
        "--bp-lg": theme.breakpoints.lg,
        "--bp-xl": theme.breakpoints.xl,

        "--font-h1": `${theme.typography.h1.fontWeight} ${theme.typography.h1.fontSize}px/${theme.typography.h1.lineHeight} inherit`,
        "--font-h2": `${theme.typography.h2.fontWeight} ${theme.typography.h2.fontSize}px/${theme.typography.h2.lineHeight} inherit`,
        "--font-h3": `${theme.typography.h3.fontWeight} ${theme.typography.h3.fontSize}px/${theme.typography.h3.lineHeight} inherit`,
        "--font-h4": `${theme.typography.h4.fontWeight} ${theme.typography.h4.fontSize}px/${theme.typography.h4.lineHeight} inherit`,
        "--font-h5": `${theme.typography.h5.fontWeight} ${theme.typography.h5.fontSize}px/${theme.typography.h5.lineHeight} inherit`,
        "--font-h6": `${theme.typography.h6.fontWeight} ${theme.typography.h6.fontSize}px/${theme.typography.h6.lineHeight} inherit`,
        "--font-big": `${theme.typography.big.fontWeight} ${theme.typography.text.fontSize}px/${theme.typography.text.lineHeight} inherit`,
        "--font-text": `${theme.typography.text.fontWeight} ${theme.typography.text.fontSize}px/${theme.typography.text.lineHeight} inherit`,
        "--font-button": `${theme.typography.button.fontWeight} ${theme.typography.button.fontSize}px/${theme.typography.button.lineHeight} inherit`,
        "--font-small": `${theme.typography.small.fontWeight} ${theme.typography.small.fontSize}px/${theme.typography.small.lineHeight} inherit`,

        "--fontsize-h1": `${theme.typography.h1.fontSize}px`,
        "--fontsize-h2": `${theme.typography.h2.fontSize}px`,
        "--fontsize-h3": `${theme.typography.h3.fontSize}px`,
        "--fontsize-h4": `${theme.typography.h4.fontSize}px`,
        "--fontsize-h5": `${theme.typography.h5.fontSize}px`,
        "--fontsize-h6": `${theme.typography.h6.fontSize}px`,
        "--fontsize-big": `${theme.typography.big.fontSize}px`,
        "--fontsize-text": `${theme.typography.text.fontSize}px`,
        "--fontsize-button": `${theme.typography.button.fontSize}px`,
        "--fontsize-small": `${theme.typography.small.fontSize}px`,

        "--fontweight-h1": theme.typography.h1.fontWeight + "",
        "--fontweight-h2": theme.typography.h2.fontWeight + "",
        "--fontweight-h3": theme.typography.h3.fontWeight + "",
        "--fontweight-h4": theme.typography.h4.fontWeight + "",
        "--fontweight-h5": theme.typography.h5.fontWeight + "",
        "--fontweight-h6": theme.typography.h6.fontWeight + "",
        "--fontweight-big": theme.typography.big.fontWeight + "",
        "--fontweight-text": theme.typography.text.fontWeight + "",
        "--fontweight-button": theme.typography.button.fontWeight + "",
        "--fontweight-small": theme.typography.small.fontWeight + "",

        "--lineheight-h1": theme.typography.h1.lineHeight + "",
        "--lineheight-h2": theme.typography.h2.lineHeight + "",
        "--lineheight-h3": theme.typography.h3.lineHeight + "",
        "--lineheight-h4": theme.typography.h4.lineHeight + "",
        "--lineheight-h5": theme.typography.h5.lineHeight + "",
        "--lineheight-h6": theme.typography.h6.lineHeight + "",
        "--lineheight-big": theme.typography.big.lineHeight + "",
        "--lineheight-text": theme.typography.text.lineHeight + "",
        "--lineheight-button": theme.typography.button.lineHeight + "",
        "--lineheight-small": theme.typography.small.lineHeight + "",

        "--color-common": theme.colors.common.base,
        "--color-common-light": theme.colors.common.light,
        "--color-common-lighter": theme.colors.common.lighter,
        "--color-common-dark": theme.colors.common.dark,
        "--color-common-darker": theme.colors.common.darker,
        "--color-common-soft": theme.colors.common.soft,
        "--color-common-softer": theme.colors.common.softer,
        "--color-common-text": theme.colors.common.text,
        "--color-common-subtext": theme.colors.common.subtext,

        "--color-brand": theme.colors.brand.base,
        "--color-brand-light": theme.colors.brand.light,
        "--color-brand-lighter": theme.colors.brand.lighter,
        "--color-brand-dark": theme.colors.brand.dark,
        "--color-brand-darker": theme.colors.brand.darker,
        "--color-brand-soft": theme.colors.brand.soft,
        "--color-brand-softer": theme.colors.brand.softer,
        "--color-brand-text": theme.colors.brand.text,
        "--color-brand-subtext": theme.colors.brand.subtext,

        "--color-accent": theme.colors.accent.base,
        "--color-accent-light": theme.colors.accent.light,
        "--color-accent-lighter": theme.colors.accent.lighter,
        "--color-accent-dark": theme.colors.accent.dark,
        "--color-accent-darker": theme.colors.accent.darker,
        "--color-accent-soft": theme.colors.accent.soft,
        "--color-accent-softer": theme.colors.accent.softer,
        "--color-accent-text": theme.colors.accent.text,
        "--color-accent-subtext": theme.colors.accent.subtext,

        "--color-info": theme.colors.info.base,
        "--color-info-light": theme.colors.info.light,
        "--color-info-lighter": theme.colors.info.lighter,
        "--color-info-dark": theme.colors.info.dark,
        "--color-info-darker": theme.colors.info.darker,
        "--color-info-soft": theme.colors.info.soft,
        "--color-info-softer": theme.colors.info.softer,
        "--color-info-text": theme.colors.info.text,
        "--color-info-subtext": theme.colors.info.subtext,

        "--color-success": theme.colors.success.base,
        "--color-success-light": theme.colors.success.light,
        "--color-success-lighter": theme.colors.success.lighter,
        "--color-success-dark": theme.colors.success.dark,
        "--color-success-darker": theme.colors.success.darker,
        "--color-success-soft": theme.colors.success.soft,
        "--color-success-softer": theme.colors.success.softer,
        "--color-success-text": theme.colors.success.text,
        "--color-success-subtext": theme.colors.success.subtext,

        "--color-warning": theme.colors.warning.base,
        "--color-warning-light": theme.colors.warning.light,
        "--color-warning-lighter": theme.colors.warning.lighter,
        "--color-warning-dark": theme.colors.warning.dark,
        "--color-warning-darker": theme.colors.warning.darker,
        "--color-warning-soft": theme.colors.warning.soft,
        "--color-warning-softer": theme.colors.warning.softer,
        "--color-warning-text": theme.colors.warning.text,
        "--color-warning-subtext": theme.colors.warning.subtext,

        "--color-danger": theme.colors.danger.base,
        "--color-danger-light": theme.colors.danger.light,
        "--color-danger-lighter": theme.colors.danger.lighter,
        "--color-danger-dark": theme.colors.danger.dark,
        "--color-danger-darker": theme.colors.danger.darker,
        "--color-danger-soft": theme.colors.danger.soft,
        "--color-danger-softer": theme.colors.danger.softer,
        "--color-danger-text": theme.colors.danger.text,
        "--color-danger-subtext": theme.colors.danger.subtext,

        ...shadows,
    }
}


export default ThemeCssVars